name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry Project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Display Foundry version
        run: forge --version

      - name: Build project with Foundry
        run: forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv
